// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4kztCAv19M19JFm_XUDTYBnP8QcYAN3w',
    appId: '1:792029717615:web:d9f2f50d88a7cc5318599a',
    messagingSenderId: '792029717615',
    projectId: 'flutter-fitness-tracker-1c26e',
    authDomain: 'flutter-fitness-tracker-1c26e.firebaseapp.com',
    storageBucket: 'flutter-fitness-tracker-1c26e.firebasestorage.app',
    measurementId: 'G-967GCVMKDB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbjp4WWH5y4QgDlG_f6jzvMTm7WGM95q0',
    appId: '1:792029717615:android:670c7cbb5f85ea5518599a',
    messagingSenderId: '792029717615',
    projectId: 'flutter-fitness-tracker-1c26e',
    storageBucket: 'flutter-fitness-tracker-1c26e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAO8fcF-F3nM86BqJXQqI_Z8msUu-rHCU4',
    appId: '1:792029717615:ios:3a7de5177c7e9b8e18599a',
    messagingSenderId: '792029717615',
    projectId: 'flutter-fitness-tracker-1c26e',
    storageBucket: 'flutter-fitness-tracker-1c26e.firebasestorage.app',
    iosBundleId: 'com.BG.calisthenicsGymApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAO8fcF-F3nM86BqJXQqI_Z8msUu-rHCU4',
    appId: '1:792029717615:ios:3a7de5177c7e9b8e18599a',
    messagingSenderId: '792029717615',
    projectId: 'flutter-fitness-tracker-1c26e',
    storageBucket: 'flutter-fitness-tracker-1c26e.firebasestorage.app',
    iosBundleId: 'com.BG.calisthenicsGymApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4kztCAv19M19JFm_XUDTYBnP8QcYAN3w',
    appId: '1:792029717615:web:51176684dd05892f18599a',
    messagingSenderId: '792029717615',
    projectId: 'flutter-fitness-tracker-1c26e',
    authDomain: 'flutter-fitness-tracker-1c26e.firebaseapp.com',
    storageBucket: 'flutter-fitness-tracker-1c26e.firebasestorage.app',
    measurementId: 'G-183WP4D1DQ',
  );

}